# Generated by Django 2.1.7 on 2019-03-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190321_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='blog_title',
        ),
    ]
